// Automated fresh-install simulation (Feature s5-feat-006, Deliverable B).
//
// Proves the plugin surface is complete and installable WITHOUT needing the
// real OpenCode runtime / GUI / a live LLM. It simulates, in-process, the two
// things a fresh-project user must wire up when following README §安装:
//
//   1. Load the plugin — `import { ghsPlugin }` and invoke it, the way
//      OpenCode's plugin loader resolves the `main` entry of
//      `golden-hoop-spell-opencode` after a `bun add` or `file:..` install.
//   2. Merge the install-time config — read `shared/opencode.json.example`
//      and assert its `plugin` + `mcp` sections reference exactly the plugin
//      entry + the codegraph MCP server (the merge a user does into their own
//      `opencode.json`).
//
// What this covers that the per-tool integration tests + full-workflow e2e do
// NOT: the integrity of the plugin REGISTRY as a single object (all 10 tools
// present under their hyphenated keys) and the correctness of the shipped
// example config. It is the cheapest possible proof that "the thing npm
// publishes installs cleanly" — no tarball unpack, no real OpenCode process.
//
// The 10-tool surface (plan §3.4 D2) is the source of truth for the key set
// assertion: init / config / plan-start / plan-review / plan-finalize /
// sprint / code / status / archive / force-archive.

import { expect, test, describe } from "bun:test";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

import { ghsPlugin } from "../../src/plugin.ts";

/** The ghs-* tools the plugin must expose (plan §3.4 D2 + s1-feat-001/002). */
const EXPECTED_TOOLS = [
  "ghs-init",
  "ghs-config",
  "ghs-plan-start",
  "ghs-plan-review",
  "ghs-plan-finalize",
  "ghs-sprint",
  "ghs-code",
  "ghs-parse-completion-signal",
  "ghs-update-feature-status",
  "ghs-status",
  "ghs-archive",
  "ghs-force-archive",
] as const;

describe("s5-feat-006 fresh-install simulation", () => {
  test("ghsPlugin exposes exactly the 12 ghs-* tools under hyphenated keys", async () => {
    // Invoke the plugin the way OpenCode's loader does: call it, read the
    // returned Hooks object. No OpenCode runtime / session input is required
    // (the plugin ignores its input — see src/plugin.ts).
    const hooks = await ghsPlugin({} as never);

    expect(hooks.tool).toBeDefined();
    const keys = Object.keys(hooks.tool ?? {}).sort();

    // Exactly the 12 expected tools — no more, no fewer, no typos.
    expect(keys).toEqual([...EXPECTED_TOOLS].sort());

    // Each entry must be a real tool definition (an object with an execute
    // function), not a stub/undefined leaked by a wiring mistake.
    for (const name of EXPECTED_TOOLS) {
      const def = hooks.tool?.[name];
      expect(def, `${name} must be registered`).toBeDefined();
      expect(typeof def?.execute, `${name} must have an execute function`).toBe("function");
    }
  });

  test("shared/opencode.json.example references the plugin entry + codegraph MCP", async () => {
    // Read the example config the way a user would (it ships in the npm
    // tarball under shared/). Parse it and assert it is the merge source for a
    // fresh project's opencode.json: a `plugin` array naming the package, and
    // an `mcp.codegraph` local server block.
    const examplePath = join(import.meta.dir, "..", "..", "shared", "opencode.json.example");
    const raw = await readFile(examplePath, "utf8");
    const cfg = JSON.parse(raw);

    // `plugin` references the published package name (matches package.json
    // `name`) — this is what makes OpenCode load our entry on startup.
    expect(Array.isArray(cfg.plugin)).toBe(true);
    expect(cfg.plugin).toContain("golden-hoop-spell-opencode");

    // `mcp.codegraph` is the codegraph MCP server (R1 path). A fresh project
    // merges this in so `codegraph_codegraph_*` tools become callable.
    expect(cfg.mcp).toBeDefined();
    expect(cfg.mcp.codegraph).toBeDefined();
    expect(cfg.mcp.codegraph.type).toBe("local");
    expect(cfg.mcp.codegraph.command).toEqual(["codegraph", "serve", "--mcp"]);

    // The example must NOT declare agents inline — per plan §Q3 / Q5 the three
    // subagents are generated by ghs-config into .opencode/agents/*.md, so the
    // example config only carries plugin + mcp.
    expect(cfg.agent ?? cfg.agents).toBeUndefined();
  });

  test("package.json files whitelist + entry point are consistent with the tarball (s5-feat-004 mirror)", async () => {
    // Mirrors the s5-feat-004 npm-pack verification (see package.json
    // `//packVerified`): the `files` whitelist ships src/ + shared/ (and not
    // test/, .ghs/, etc.), `main` points at the plugin entry, and the package
    // name matches what opencode.json.example references. Kept in the e2e
    // suite so a regression that breaks installability is caught by `bun test`
    // before it reaches a real npm publish.
    const pkgPath = join(import.meta.dir, "..", "..", "package.json");
    const pkg = JSON.parse(await readFile(pkgPath, "utf8"));

    expect(pkg.name).toBe("golden-hoop-spell-opencode");
    expect(pkg.main).toBe("src/index.ts");

    const files = pkg.files as string[] | undefined;
    expect(files, "package.json must declare a files whitelist").toBeDefined();
    expect(files).toContain("src");
    expect(files).toContain("shared");
    // The whitelist must NOT ship tests or project tracking — those are dev-only.
    expect(files).not.toContain("test");
    expect(files).not.toContain(".ghs");
    expect(files).not.toContain("spikes");

    // The shipped entry must resolve to the real plugin — index.ts
    // default-exports ghsPlugin (verified structurally above).
    const indexPath = join(import.meta.dir, "..", "..", pkg.main);
    const indexSrc = await readFile(indexPath, "utf8");
    expect(indexSrc).toContain("ghsPlugin");
  });
});
